### ISSUE TITLE
The NPM install instructions are incorrect because the package name is parked

### ISSUE THREAD

**Issue by nschonni** [dequelabs/axe-cli#1]
The NPM package is currently parked with the NPM security holding package https://www.npmjs.com/package/axe-cli#security-holding-package

**Comment by lbjones** [comment]
So in the meantime...  Is there a way that this code can be executed, or is this project unusable until then?

**Comment by dylanb** [comment]
@WilcoFiers can you please check into why the npm package name has been captured?

**Comment by marcysutton** [comment]
We have it, we just haven't pushed to it yet. Working on it now

**Comment by marcysutton** [comment]
The way to run it pre-release if you have Selenium Webdriver installed is to execute the index file instead of the axe binary:

`node index.js www.someurl.com`

**Comment by lynnco** [comment]
Heya! I appreciate ya'll working on this. I was thinking that it might save some people a few minutes of searching to add "Work In Progress" label to the readme? I can send a PR for that

**Comment by marcysutton** [comment]
Thanks @lynnco but I already took care of it.

**Comment by marcysutton** [comment]
This has now been published. Let us know if you run into any issues! https://www.npmjs.com/package/axe-cli/
