### ISSUE TITLE
Security vulnerability through phantomjs-prebuilt

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-cli#10]
`phantomjs-prebuilt->extract-zip->concat-stream`

https://snyk.io/vuln/npm:concat-stream:20160901

**Comment by JayKid** [comment]
Isn't this no longer relevant since https://github.com/dequelabs/axe-cli/commit/1ae8e12030bd2fc2ffa1c7663e62b59c692b4f54 ?
