### ISSUE TITLE
Axe only works with Chrome version must be between 71 and 75 

### ISSUE THREAD

**Issue by bolonio** [dequelabs/axe-cli#104]
When running axe in the terminal, I got the error:

`SessionNotCreatedError: session not created: Chrome version must be between 71 and 75`

Could you please upgrade the version of Chrome supported?

Thanks :)

**Comment by marcinkrzeminski** [comment]
Hey @bolonio 

Having the same issue. 

What I did to quickly fix it on my local.

1. Clone the repo
2. Open `package.json` and update the `chromedriver` dependency to match your needs. In my case  `"chromedriver": "^76",` works just fine.
3. `yarn install`
4. `npm link`

After those steps I was able to run axe from the cli.

Hope that helps ;).

**Comment by thedrow** [comment]
That's a workaround but not a fix.
Can we please fix it?

**Comment by bolonio** [comment]
Hi @marcinkrzeminski,

Thanks for the answer, but as @thedrow mentioned, that's definitely a workaround. I think this should be fixed (supported) by the core team.

Thanks anyway :)

**Comment by straker** [comment]
Closed via #105

**Comment by thedrow** [comment]
Can we please release a new version?

**Comment by straker** [comment]
Version 3.1.1. was released
