### ISSUE TITLE
Contrast-check returns false positives

### ISSUE THREAD

**Issue by boyum** [dequelabs/axe-cli#12]
I haven't really looked into the maths at this one, but I suspect that this isn't correct.

I get this error: 
![image](https://cloud.githubusercontent.com/assets/9085189/24446656/96137426-146e-11e7-9bf4-dbb2b2a5accc.png)

On this part of the page (specifically the dates):
![image](https://cloud.githubusercontent.com/assets/9085189/24446675/a1f28b24-146e-11e7-906d-86c980c241c1.png)

Having these color values (contrast ratio: 12.7:1):
![image](https://cloud.githubusercontent.com/assets/9085189/24446645/8e1222fe-146e-11e7-8af9-72ab965f8711.png)

It would be nice if the cli returned the values it calculated. In this case, it might be triggered by the font-size, which is 16px.

**Comment by dylanb** [comment]
Can you open an issue for this on the axe-core project please https://github.com/dequelabs/axe-core

**Comment by marcysutton** [comment]
If you can reproduce it with axe-core, that is. If it's limited to axe-cli, we'll want to document it here. I mention that because I've seen differences in what gets returned by axe-cli depending on the driver (ex. PhantomJS or Chrome).

**Comment by boyum** [comment]
The aXe Chrome extension does not find any violation on the same page. I will try using the npm package tomorrow, to see if that finds anything.

**Comment by marcysutton** [comment]
@boyum did you ever run your code with axe-core to find out? I agree that axe-cli should report the contrast ratio and colors in the result–I was surprised to find it was super light on reporting.

**Comment by boyum** [comment]
No, I never did, sorry. Will really try to remember this tomorrow, haha.

**Comment by boyum** [comment]
@marcysutton axe-core returns no violations, as it should.

**Comment by dylanb** [comment]
closing due to no issue

**Comment by marcysutton** [comment]
I think that means there is an issue with axe-cli–it was returning issues that axe-core wasn't.

**Comment by marcysutton** [comment]
@boyum can you provide us with a test case so we can debug those issues? An HTML file would be ideal so we can isolate your contrast results with axe-cli.

**Comment by boyum** [comment]
Unfortunately, I cannot seem to reproduce this error anymore, on the exact same page. I don't think it was, but it might very well have been a user error. 

However, I might have discovered something else: Axe-cli run with Hyper (https://github.com/zeit/hyper) consequently returns 3 issues on http://orkide.preprod.acos.no, while Command Prompt and PowerShell returns only one issue. I'll file this as a seperate issue if you want me to.

Keep up the good work!
