### ISSUE TITLE
Drop Node v6/v7 support

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/axe-cli#133]
According to [Node's release documentation](https://nodejs.org/en/about/releases/), v6/v7 are no longer supported.

To fix, change this to https://github.com/dequelabs/axe-cli/blob/develop/package.json#L6-L8 ">=8".

**Comment by jeankaplansky** [comment]
no user-facing rule help required.

**Comment by padmavemulapati** [comment]
No more less than v8 seeing for Node now. Using `node -v`  /  ` v8.9.4`
