### ISSUE TITLE
Custom Chrome Flags docs leads to a blogpost that no longer loads

### ISSUE THREAD

**Issue by sw-yx** [dequelabs/axe-cli#141]
[On the docs](https://github.com/dequelabs/axe-cli/#custom-chrome-flags) we link to an external site: https://peter.sh/experiments/chromium-command-line-switches/ for  flags to configure how the browser functions

but it currently looks like this:

![image](https://user-images.githubusercontent.com/6764957/76989968-956ae480-691d-11ea-9b92-f47312868a23.png)

if anyone has a list of these flags, I suggest copying over those flags here, or finding a better link.

**Comment by straker** [comment]
Odd, it currently loads for me in latest Chrome:

![image](https://user-images.githubusercontent.com/2433219/77002959-11ffc200-6922-11ea-82be-258ac0e29678.png)

**Comment by sw-yx** [comment]
i see it too now. seems temporary. :shrug:
