### ISSUE TITLE
License info inconsistent between package.json vs LICENSE

### ISSUE THREAD

**Issue by dbjorge** [dequelabs/axe-cli#142]
The `LICENSE` file at the root of the repo suggests that the project is MPL-2.0 licensed, but `package.json` lists "ISC" as the license. The two should be consistent, but I didn't send a PR for the change because I wasn't sure which way you wanted to resolve the issue. The project was presumably intended to be MPL-2.0, but it's unclear to me whether you'd want to treat updating package.json as a minor change vs a major breaking change.

**Comment by straker** [comment]
Thanks for letting us know. I got confirmation on which license we should have and updated the package.json file accordinly.
