### ISSUE TITLE
custom axe-core new rule not run

### ISSUE THREAD

**Issue by aarontk** [dequelabs/axe-cli#24]
I created a custom axe-core with a new rule to verify if there are any headings on the page. The run never seemed to run. To verify my axe-core was being used, I modified an existing rule and verified the modified rule was executed. I'm using a local webserver so I have access to the code. I added a script element with the src attribute pointing to my axe-core. I ran the axe cli again and this time my new rule was executed.

**Comment by WilcoFiers** [comment]
This problem seems related to what you've already reported here:
https://github.com/dequelabs/axe-webdriverjs/issues/38

I'm closing this as a duplicate, and we'll continue on the other issue.
