### ISSUE TITLE
timer for waiting for page to fully load

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-cli#33]
It looks like --timeout allows the user to set an automatic timeout for long pages, but is it possible to set a "wait" so that a page can complete loading of all resources before axe runs?

**Comment by WilcoFiers** [comment]
You are right. The timeout option lets you change how long webdriver will wait before deciding the page isn't going to load. But there is no option that lets you delay after loading. Axe-cli attempts to determine when the browser is done, which is does fairly well, but if things get pulled in after the load, there's no consistent way to determine that. We could possibly add a `-load-delay` option to do something like that?

**Comment by kensgists** [comment]
Yes, a `--load-delay` option would be helpful for such cases. Thanks.

**Comment by AkshanshSrivastava03** [comment]
Hi @WilcoFiers, 
Is --load-delay option incorporated in axe-cli?

**Comment by WilcoFiers** [comment]
This isn't currently being worked on. We'd welcome a pull request to add this feature.

**Comment by JayKid** [comment]
Sorry @WilcoFiers , I forgot to add docs for it.. so I created a small (1-commit) PR for it 🙈 :

https://github.com/dequelabs/axe-cli/pull/54

**Comment by WilcoFiers** [comment]
Yikes! Can't believe I missed that :/ Glad you spotted it.

**Comment by kensgists** [comment]
Hi @WilcoFiers and @JayKid, has this landed in prod yet?

Also (perhaps another feature request) would there be a way to, in addition to an set delay, have axe-cli wait on the rendering of an element?

**Comment by WilcoFiers** [comment]
@kensgists We released axe-cli 3.0 yesterday :)
