### ISSUE TITLE
[feature request] blacklist/whitelist selectors

### ISSUE THREAD

**Issue by jasonday** [dequelabs/axe-cli#44]
Use case: As part of continuous integration with react, the devs want a feedback loop on accessibility issues as part of development. However, when using axe it executes against the full rendered page and in some scenarios when that developer is working on a specific component, they want accessibility feedback for that component only. 

Having the capability to whitelist or blacklist selectors, would allow for testing specific components and outputting reports (and failing builds) surrounding that component.

**Comment by marcysutton** [comment]
axe-cli already has include and exclude, which is the same API you'd get in axe-core. Does that not work for you? https://github.com/dequelabs/axe-cli#defining-the-scope-of-a-test

**Comment by jasonday** [comment]
@marcysutton - my apologies. Somehow the dev and I both missed that feature.
