### ISSUE TITLE
Unknown error when using chrome

### ISSUE THREAD

**Issue by simi823** [dequelabs/axe-cli#47]
Trying to test a page using Chrome, and after Chrome opens the page it gives the following error:
Running axe-core 2.6.0 in chrome

Testing http://www.nj.com/news ... please wait, this may take a minute.

An error occurred while testing this page.
Please report the problem to: https://github.com/dequelabs/axe-cli/issues/

How can I find more information on the error to troubleshoot?

**Comment by marcysutton** [comment]
It works for me, both from the develop branch and the distributed version. Can you try again?

**Comment by simi823** [comment]
yes, I tried it again... Had to upgrade the Chrome browser and chromedriver and it worked. Sorry to jump the gun and post this!
