### ISSUE TITLE
cannot set path and executable to the browser

### ISSUE THREAD

**Issue by masi** [dequelabs/axe-cli#60]
On Windows I tried to use axe-cli with a PortableApps.com version. For such a case seting up PATH won't be enough as the binary is called GoogleChromePortable.exe. So I need to set the full path (or path and filename).

Ok, this is probably rare, but I guess passing the path to axe-cli as a parameter is a nice thing to have.

Masi

PS: Pointers so I can try my luck adding this feature for myself are welcome.

**Comment by WilcoFiers** [comment]
You'll probably need to make a change to `lib/webdriver.js`, pass it in as an argument to `startDriver()`. Not sure how to have it load a browser on a different path, but I'm sure if you dig deep enough into the Selenium docs you'll find it there. Be sure not to limit this to just Chrome though. If we add such a feature it should work for other browsers.

**Comment by stephenmathieson** [comment]
@masi is this still relevant?
