### ISSUE TITLE
can you login to a site?

### ISSUE THREAD

**Issue by kevinchugh** [dequelabs/axe-cli#78]
Is there a way to specify authentication elements, and programmatically login for testing?

**Comment by stephenmathieson** [comment]
Not with the CLI, no. Instead, we suggest you use [`axe-webdriverjs`](https://github.com/dequelabs/axe-webdriverjs) or [`axe-puppeteer`](https://github.com/dequelabs/axe-puppeteer) to get more fine-grained control over the site you're testing.
