### ISSUE TITLE
Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by calumryan** [dequelabs/axe-cli#92]
Trying to figure out if this issue is due to something in my script or a markup issue?

`$ axe calumryan.com`

`axe-webdriverjs deprecated Error must be handled as the first argument of axe.analyze. See: #83 ../../usr/local/lib/node_modules/axe-cli/lib/axe-test-urls.js:85:8
/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^
JavascriptError: javascript error: Cannot read property 'run' of undefined`

**Comment by straker** [comment]
Interesting. I ran the command as you posted and didn't get an error (could be due to a redesign of the site). Are you still seeing this error?

**Comment by straker** [comment]
Nm. Found a related issue with a solution https://github.com/dequelabs/axe-cli/issues/76#issuecomment-460246385. We'll be creating a release soon so this issue should be fixed by a new release.

**Comment by BeratBulbul** [comment]
anladıysam siksiner
