### ISSUE TITLE
Checkstyle format support

### ISSUE THREAD

**Issue by GWillmann** [dequelabs/axe-cli#95]
Hi,

In order to be able to automatically parse the results of your wonderful cli in CI such as Jenkins, we would need a output file in Checkstyle format.

Do you guys think it could be possible?

Thanks for your help.

**Comment by straker** [comment]
Unfortunately we don't have any plans to convert the output to different formats. You might be able to do something similar to https://github.com/foiseworth/flow-json-to-checkstyle-xml to convert the JSON results into Checkstyle format.
