### ISSUE TITLE
unknown option `--stdout'

### ISSUE THREAD

**Issue by kylegrover** [dequelabs/axe-cli#98]
Hi, I installed axe-cli today (3.0.0 on Mac, using Homebrew) and I'm trying to configure it to pass json to jq before saving. When I run this command:

> To pipe the results to a JSON-parsing program for further processing, do:
> `axe --stdout www.deque.com | jq ".[0].violations"`

I get `error: unknown option '--stdout'`.

**Comment by straker** [comment]
Thanks for letting us know. The npm release is a year old and the `--stdout` option was added afterwards. We'll work on creating a new release soon so it's available.

**Comment by straker** [comment]
Release created. `--stdout` option should now be available in v3.1.0
